org: akaviles024
app: aws-node
service: aws-node
frameworkVersion: "3"
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - kafka:
          accessConfigurations:
            saslPlainAuth: arn:aws:secretsmanager:us-east-1:014920475271:secret:kafka/orders-M1JSqj
          bootstrapServers: pkc-n98pk.us-west-2.aws.confluent.cloud:9092
          topic: output-topic
          batchSize: 100
          startingPosition: LATEST

resources: # CloudFormation template syntax
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: ordersTable
        AttributeDefinitions:
          - AttributeName: ordertime
            AttributeType: N
          - AttributeName: orderid
            AttributeType: N
          - AttributeName: itemid
            AttributeType: S
          - AttributeName: address
            AttributeType: S
        KeySchema:
          - AttributeName: ordertime
            KeyType: RANGE
          - AttributeName: orderid
            KeyType: HASH
          - AttributeName: itemid
            KeyType: RANGE
          - AttributeName: address
            KeyType: RANGE
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1
