org: akaviles024
app: aws-node
service: aws-node
frameworkVersion: "3"
configValidationMode: warn

provider:
  name: aws
  runtime: nodejs18.x

functions:
  function1:
    handler: index.handler
    events:
      - kafka:
          bootstrapServers: pkc-n98pk.us-west-2.aws.confluent.cloud:9092
          topic: orders
          batchSize: 1
          startingPosition: LATEST
